### ISSUE TITLE
Unable to run on Piwik 3.0.1

### ISSUE THREAD

**Issue by FlorentCoppint** [nebev/piwik-cli-setup#3]
Hi,
Running script with Piwik 3.0.1 leads to : 

```
2017-01-17 12:27:10 - Running Piwik Initial Install Script
2017-01-17 12:27:10 - Preparing Cache and Diagnostics
Uncaught exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'piwik.piwik_option' doesn't exist
in /var/www/piwik/libs/Zend/Db/Adapter/Pdo/Abstract.php line 280
#0 /var/www/piwik/core/Db.php(168): Zend_Db_Adapter_Pdo_Abstract->exec('DELETE FROM `pi...')
#1 /var/www/piwik/plugins/Diagnostics/Diagnostic/LoadDataInfileCheck.php(61): Piwik\Db::exec('DELETE FROM `pi...')
#2 /var/www/piwik/plugins/Diagnostics/DiagnosticService.php(61): Piwik\Plugins\Diagnostics\Diagnostic\LoadDataInfileCheck->execute()
#3 /var/www/piwik/plugins/Diagnostics/DiagnosticService.php(48): Piwik\Plugins\Diagnostics\DiagnosticService->run(Array)
#4 /var/www/install-piwik.php(92): Piwik\Plugins\Diagnostics\DiagnosticService->runDiagnostics()
#5 /var/www/install-piwik.php(72): PiwikCliInstall->prepare()
#6 /var/www/install-piwik.php(57): PiwikCliInstall->install()
#7 {main}

```

Of course "piwik.piwik_option" does not exist, I except this script to create all necessary tables...

**Comment by nebev** [comment]
I'm successfully running this on brand-new installs of Piwik 3.0.2.
Are you 100% sure that some tables don't already exist? If they do, the initial database population function may not run.

**Comment by avindra** [comment]
Trying this out on a new install of Piwik 3.1.0:

Everything goes through, but when I try to log in to piwik, it infinitely loads a header:

![image](https://user-images.githubusercontent.com/126848/31790599-0bb6d040-b4e4-11e7-88e1-581f20b881f0.png)

Any ideas what's happening?

**Comment by anilkotapati** [comment]
Is there a way where we can add ssl details for the database which piwik can communicate with.
